### ISSUE TITLE
Be notified of the end of breaks

### ISSUE THREAD

**Issue by dkrmr** [TatriX/pomidor#9] opened 2017-11-22 16:07 UTC
Title says it all. I'll be nice to have the same notification system, alert+sound, to mark the end of breaks.

**Comment by TatriX** [comment] 2017-11-22 16:12
Sounds good. I'll try to add one.

**Comment by dkrmr** [comment] 2017-12-14 15:02
Or just a hook.

**Comment by TatriX** [comment] 2017-12-14 15:24
You can use existing hook currently:
```elisp
(defun my-pomidor-update-hook ()
  (let ((break-duration 30) ;; seconds
        (ellapsed (time-to-seconds (pomidor-overwork-duration))))
    (when (> ellapsed break-duration)
      (pomidor-play-sound-file-async pomidor-sound-overwork))))

(add-hook 'pomidor-update-hook #'my-pomidor-update-hook)
```

**Comment by dkrmr** [comment] 2017-12-16 10:10
That doesn't works. It plays the overwork sound every 30 seconds :/

**Comment by TatriX** [comment] 2017-12-16 10:16
See `pomidor-default-alert`.
You may want to add `alert` call to your hook
```elisp
(alert (format "Work!\Break: [%s]"
                   (format-time-string "%H:%M:%S" (pomidor-break-duration) t))
           :severity 'normal
           :icon pomidor-icon
           :title "Pomidor"
           :category 'pomidor)
```

**Comment by vfinotti** [comment] 2018-01-05 14:58
I am experiencing the same problem. This issue is caused by the `pomidor-break-duration` function, that returns a big number when `:break` is `nil`. I have describe the issue and presented a possible fix in pull request #11.

**Comment by TatriX** [comment] 2018-03-12 13:51
Closed in https://github.com/TatriX/pomidor/commit/5780ce2aaa98882a79e92f5eefaaf10fd8dbee3a

**Closed by TatriX** 2018-03-12 13:51 UTC
Labels: PR welcome
